FROM python:3.10-slim

# -------- System Dependencies --------
RUN apt-get update && apt-get install -y \
    tesseract-ocr \
    libgl1 \
    && rm -rf /var/lib/apt/lists/*

# -------- Workdir --------
WORKDIR /app

# -------- Copy requirements --------
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

# -------- Copy app --------
COPY . .

# -------- Expose port --------
EXPOSE 8000

# -------- Run FastAPI --------
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
